---
title: "R Notebook"
output: html_notebook
---

Exercise 12.1
```{r}
install.packages('tidyverse')
library(tidyverse)
```

Exercise 12.2
```{r}
scores <- 
  tibble(
    name = c("mike", "carol", "greg", "marcia", "peter", "jan", "bobby", "cindy", "alice"),
    school = c("south", "south", "south", "south", "north", "north", "north", "south", "south"),
    teacher = c("johnson", "johnson", "johnson", "johnson",  "smith", "smith", "smith", "perry", "perry"),
    sex = c("male", "female", "male", "female", "male", "female", "male", "female", "female"),
    math_score = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
    reading_score = c(1, 5, 2, 4, 5, 4, 1, 5, 4)
)
```

Exercise 12.3
```{r}
view(scores)
```

Exercise 12.4
```{r}
scores_small <- scores %>%
  slice(1:3)
scores_small
```

Exercise 12.5
```{r}
arrange(scores,desc(math_score))
```

Exercise 12.6
```{r}
arrange(scores, name)
```

Exercise 12.7

```{r}
arrange(scores, sex)
```

Exercise 12.8
```{r}
scores %>% 
  group_by(sex) %>% 
  summarise(mean(math_score), mean(reading_score))
```

EXERCISE 12.8
```{r}
scores %>% 
  arrange(school, teacher, sex)
```

Exercise 12.9
```{r}
scores %>% 
  select(name, math_score,reading_score)
```

Exercise 12.10
```{r}
scores %>% 
  select(-sex)
```

Exercise 12.11
```{r}
scores %>% 
  select(-c(math_score,reading_score))
```

Exercise 12.12
```{r}
scores %>% 
  select(sex, everything())
```

Exercise 12.13
```{r}
scores %>% 
  filter(school == 'south' & sex == 'male')
```

Exercise 12.14
```{r}
scores %>% 
  filter(math_score >3)
```

Exercise 12.15

```{r}
scores %>% 
  filter(math_score >=4 & reading_score >=3) %>% 
  nrow()
```

Exercise 12.17
```{r}
scores %>% 
  filter(reading_score == 2 | reading_score == 3 | reading_score == 4)
```

Exercise 12.18
```{r}
scores %>% 
  filter(substr(name,1,1) == 'm')
```

Exercise 12.19
```{r}
scores %>% 
  group_by(teacher) %>% 
  filter(math_score == 5)
```

Exercise 12.20
```{r}
scores %>% 
  group_by(sex) %>% 
  filter(mean(math_score) == 4)
```

Exercise 12.21
```{r}
scores %>% 
  mutate('math_reading_avg' = (math_score + reading_score)/2)
```

Exercise 12.23
```{r}
scores %>% 
  mutate('higher_math_achiver' = (math_score >= 4))
```

```{r}
scores %>% 
  group_by(teacher) %>% 
  mutate('reading_score_by_teacher' = reading_score - mean(reading_score))
```

Exercise 12.28
```{r}
scores %>% 
  group_by(teacher) %>% 
  mutate('number_of_students_in_class' = n())
```

Exercise 12.29
```{r}
scores %>% 
  summarise(mean(math_score))
```

Exercise 12.30
```{r}
scores %>% 
  summarise(median(math_score), median(reading_score))
```

```{r}
scores %>% 
  group_by(school) %>% 
  summarize(min(math_score))
```

```{r}
scores %>% 
  group_by(teacher) %>% 
    summarize(max(math_score))

```

```{r}
scores %>% 
  select(name, math_score) %>% 
  mutate('math_score_ec' = math_score +5) %>% 
  arrange(math_score_ec)
```

```{r}
scores %>% 
  filter(teacher != 'smith') %>%
  group_by(sex) %>% 
  summarise(mean_math_score = mean(math_score))
```

